### ISSUE TITLE
Error: EACCES: permission denied, lstat '/root/directory'

### ISSUE THREAD

**Issue by MattiaFailla** [actions/upload-artifact#130]
**Describe the bug**
Trying to upload a directory located under root lead to EACCES error

**Version**
- [ ] V1
- [x] V2

**Environment**
- [ ] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

**Screenshots**
![image](https://user-images.githubusercontent.com/11872425/94339661-caa66c80-fffb-11ea-9358-49ee97546fbf.png)

**Run/Repo Url**
https://github.com/nextblu/spacecoin-docker/actions/runs/273850769

**How to reproduce**
Try to upload an artifact located in `/root/`

**Comment by l0b0** [comment]
I tried to `sudo chmod --recursive 0755 /redacted` the relevant directories, but even then the upload fails:

> EACCES: permission denied, lstat '/redacted'

Is there some SELinux rule I have to disable or something to be able to read files?

**Comment by konradpabjan** [comment]
v4 has shipped officially today and recommend switching over as this should be fixed. https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/

v1-v3 used to use `stat` and/or `lstat` to do a bunch of calculations to file sizes and other things but that is no longer the case

**Comment by MattiaFailla** [comment]
@konradpabjan I can confirm this has been fixed in the new version.

**Comment by mwithi** [comment]
Hello, I still have this problem with v4, @MattiaFailla please was this the same intent of your?

https://github.com/informatici/openhospital-api/actions/runs/7467924455/job/20322390283?pr=421#step:10:12
