### ISSUE TITLE
Zipped Artifact Downloads corrupt/incomplete

### ISSUE THREAD

**Issue by annamariaratajczak** [actions/upload-artifact#156]
**Describe the bug**
When pressing the download button for the Allure report artifact it should:
- Start downloading immediately
- Download a zip file of approx >10 MB
- zip file to contain correct directory structure of the uploaded artifacts from the job

**Version**
- [actions/upload-artifact@v2 ] V2

**Environment**
- [ubuntu 18 ] Linux

**How to reproduce**
1. Run a workflow (with allure report configured)
2. Click on the allure report in the artifacts.
3. Download waits for about 30 seconds at 0 bytes/sec. Download finishes after 64kB of data.
The resulting zip is corrupted, containing only empty directories.

Note: 
JUnit zip files and logs are not corrupted.

**Comment by konradpabjan** [comment]
If you retry the artifact download does the issue persist? I've seen some reports where there is a corrupted zip but retrying the download always seems to do the trick

https://github.com/actions/upload-artifact/issues/74#issuecomment-622314051

**Comment by tazzvio** [comment]
We seem to have a similar problem. One day it's working and our zip contains a correct zip another day the zip is corrupted.

**Comment by prescod** [comment]
I wrote the following script to demonstrate the problem.

Today is American Thanksgiving and I note that the downloads are lightning fast and highly reliably. Yesterday they took 10 times as long as were extremely unreliable (as much as 50% error rate)

```
import os
import sys
import zipfile

import requests

github_token = os.environ["GH_REPO_TOKEN"]
artifact_id = os.environ["GH_ARTIFACT_ID"]

url = f"https://api.github.com/repos/SFDO-Tooling/CumulusCI/actions/artifacts/{artifact_id}/zip"


def try_download():
    response = requests.get(url, headers={"Authorization": f"token {github_token}"})

    with open("/tmp/zipfile.zip", "wb") as f:
        f.write(response.content)

    try:
        with zipfile.ZipFile("/tmp/zipfile.zip") as z:
            print(len(z.infolist()))
            return True
    except zipfile.BadZipFile as e:
        return False


def doit():
    successes = failures = 0

    for i in range(10):
        if try_download():
            successes += 1
        else:
            failures += 1

        print("Successes", successes, "Failures", failures)


doit()
```

**Comment by HasinduLanka** [comment]
I'm having the same issue on https://github.com/spindlygo/spindly-demo

I'm running 3 almost identical scripts (NPM build + Golang build) on linux, windows and mac runners.

![2021-12-30_22-59_2](https://user-images.githubusercontent.com/35098511/147775195-2fb06f27-de80-4a1d-9263-625661cb027c.png)

Sometimes, one or two of the downloaded ZIP files are corrupted. Tried downloading multiple times.

![2021-12-30_22-54](https://user-images.githubusercontent.com/35098511/147775322-575c06c1-3518-4b9f-8828-750de8c8bef6.png)

But this issue magically disappear after running the same workflow again, without changes.

![2021-12-30_22-58](https://user-images.githubusercontent.com/35098511/147775465-9c1a133f-b15f-4631-8865-9ae115da69e0.png)

**Comment by pengzhendong** [comment]
Same issue. Any progress?

**Comment by deya-eldeen** [comment]
happens with me.

**Comment by MAHBOD-85** [comment]
![Screenshot_20221027-133525_Chrome](https://user-images.githubusercontent.com/78406810/198256403-ef184e15-99cb-4a44-a6dd-623c94bccb29.jpg)
Github actions
My beloved

**Comment by kirillt** [comment]
Happens with me as well. Any treatment?

**Comment by kirillt** [comment]
This time it failed 5 times in a row. Opened another Firefox profile, tried again: downloaded correctly and almost instantly while it was really slow before.

Browser-related issue?

**Comment by RudraSen2** [comment]
Mine was working after I extracted the file containing my iso artifact using windows instead of 7-zip which I was doing earlier.

**Comment by konradpabjan** [comment]
We've released v4 upload-artifact today! https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/

Recommend switching over as what you're describing should no longer happen. Uploads overall should be faster and more reliable and we even output a SHA256 value for the upload artifact. 

In the UI when download artifacts, they should start instantly now and will always be consistent if the artifacts are uploaded using v4. 

The biggest thing too is that the artifacts should no longer be corrupt as well. There is a small chance today with v1-v3 that there can be errors but with v4 this should no longer happen

**Comment by michal2612** [comment]
> We've released v4 upload-artifact today! https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/
> 
> Recommend switching over as what you're describing should no longer happen. Uploads overall should be faster and more reliable and we even output a SHA256 value for the upload artifact.
> 
> In the UI when download artifacts, they should start instantly now and will always be consistent if the artifacts are uploaded using v4.
> 
> The biggest thing too is that the artifacts should no longer be corrupt as well. There is a small chance today with v1-v3 that there can be errors but with v4 this should no longer happen

This fixes the problem for Github.com. I still experience this issue on GHSE.
